from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables import RunnablePassthrough
from src.langchain_module.models import get_llm
from src.langchain_module.prompts import CHAT_PROMPT
from src.data_layer.vector_store import VectorStoreManager
from src.utils.metadata_parser import extract_filters_with_llm
from src.utils.logger import logger

def create_ecommerce_chain():
    llm = get_llm()
    vs_manager = VectorStoreManager()
    db = vs_manager.get_vector_db()

    # 1. CONTEXTUALIZATION LOGIC 
    # This rephrases the user's question to include context from history
    contextualize_q_system_prompt = (
        "Given a chat history and the latest user question "
        "which might reference context in the chat history, "
        "formulate a standalone question which can be understood "
        "without the chat history. Do NOT answer the question, "
        "just reformulate it if needed and otherwise return it as is."
    )
    
    contextualize_q_prompt = ChatPromptTemplate.from_messages([
        ("system", contextualize_q_system_prompt),
        MessagesPlaceholder("chat_history"),
        ("human", "{question}"),
    ])
    
    # This sub-chain creates the 'standalone_question'
    contextualize_q_chain = contextualize_q_prompt | llm | StrOutputParser()

    # --- 2. RETRIEVAL LOGIC ---
    def retrieve_context(input_data):
        # We now use the standalone question generated by the LLM
        standalone_query = input_data["standalone_question"]
        
        # Extracted filters from the rephrased query (e.g., "HP laptops under 50k")
        chroma_filter = extract_filters_with_llm(standalone_query)
        logger.info(f"Contextualized Query: {standalone_query}")
        logger.info(f"Extracted Filters: {chroma_filter}")

        docs = db.similarity_search(standalone_query, k=5, filter=chroma_filter if chroma_filter else None)
        
        if not docs:
            docs = db.similarity_search(standalone_query, k=5)

        return "\n\n".join([doc.page_content for doc in docs])

    # --- 3. FINAL CHAIN ASSEMBLY ---
    chain = (
        RunnablePassthrough.assign(
            standalone_question=contextualize_q_chain
        )
        | RunnablePassthrough.assign(
            context=retrieve_context
        )
        | CHAT_PROMPT 
        | llm 
        | StrOutputParser()
    )
    
    return chain